import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';

/* Mock Automations Database */
let automationsDB = [
  {
    id: 'AUTO-001',
    type: 'low_stock',
    name: 'Low Stock Alert',
    description: 'Get notified when product stock goes below threshold',
    enabled: true,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'immediate',
    threshold: 10,
    categories: ['all'],
    messageTemplate: 'low_stock_alert',
    customMessage: '🚨 *Low Stock Alert*\n\nProduct: {{product_name}}\nCurrent Stock: {{current_stock}} units\nThreshold: {{threshold}} units\n\nAction Required: Restock immediately.\n\n_EHN One - Inventory System_',
    lastTriggered: new Date('2024-06-10T09:30:00'),
    triggeredCount: 12,
  },
  {
    id: 'AUTO-002',
    type: 'payment_reminder',
    name: 'Payment Due Reminder',
    description: 'Remind customers about pending payments',
    enabled: true,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'daily',
    daysBeforeDue: 3,
    messageTemplate: 'payment_reminder',
    customMessage: '💰 *Payment Reminder*\n\nHello {{customer_name}},\n\nThis is a friendly reminder that payment of *₹{{amount}}* for Invoice #{{invoice_number}} is due on {{due_date}}.\n\nPlease make the payment at your earliest convenience.\n\nThank you!\n_EHN One Team_',
    lastTriggered: new Date('2024-06-14T10:00:00'),
    triggeredCount: 45,
  },
  {
    id: 'AUTO-003',
    type: 'stock_report',
    name: 'Daily Stock Report',
    description: 'Daily summary of inventory status',
    enabled: false,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'daily',
    time: '09:00',
    messageTemplate: 'stock_report',
    customMessage: '📊 *Daily Stock Report*\n\nDate: {{date}}\n\n📦 Total Products: {{total_products}}\n✅ In Stock: {{in_stock}}\n⚠️ Low Stock: {{low_stock}}\n❌ Out of Stock: {{out_of_stock}}\n\n_Generated by EHN One_',
    lastTriggered: new Date('2024-06-13T09:00:00'),
    triggeredCount: 28,
  },
  {
    id: 'AUTO-004',
    type: 'order_confirmation',
    name: 'Order Confirmation',
    description: 'Send order confirmation to customers',
    enabled: true,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'immediate',
    includeInvoice: true,
    messageTemplate: 'order_confirmation',
    customMessage: '✅ *Order Confirmed*\n\nThank you {{customer_name}}!\n\nOrder ID: {{order_id}}\nTotal Amount: ₹{{amount}}\nDelivery Date: {{delivery_date}}\n\nYour invoice is attached.\n\n_EHN One - Thank you for your business!_',
    lastTriggered: new Date('2024-06-15T14:20:00'),
    triggeredCount: 89,
  },
];

let nextAutoNum = 5;

/* WhatsApp Business API Configuration */
let whatsappConfig = {
  apiKey: '',
  phoneNumberId: '',
  businessAccountId: '',
  webhookUrl: '',
  isConfigured: false,
  verificationStatus: 'pending', // pending, verified, failed
};

// Import global settings function (will be set from Settings page)
export const getWhatsAppConfig = () => whatsappConfig;
export const setWhatsAppConfig = (config) => { whatsappConfig = config; };

/* Message Template Library */
const messageTemplates = {
  low_stock_alert: {
    name: 'Low Stock Alert',
    variables: ['product_name', 'current_stock', 'threshold'],
    defaultMessage: '🚨 *Low Stock Alert*\n\nProduct: {{product_name}}\nCurrent Stock: {{current_stock}} units\nThreshold: {{threshold}} units\n\nAction Required: Restock immediately.\n\n_EHN One - Inventory System_',
  },
  payment_reminder: {
    name: 'Payment Reminder',
    variables: ['customer_name', 'amount', 'invoice_number', 'due_date'],
    defaultMessage: '💰 *Payment Reminder*\n\nHello {{customer_name}},\n\nThis is a friendly reminder that payment of *₹{{amount}}* for Invoice #{{invoice_number}} is due on {{due_date}}.\n\nPlease make the payment at your earliest convenience.\n\nThank you!\n_EHN One Team_',
  },
  stock_report: {
    name: 'Stock Report',
    variables: ['date', 'total_products', 'in_stock', 'low_stock', 'out_of_stock'],
    defaultMessage: '📊 *Daily Stock Report*\n\nDate: {{date}}\n\n📦 Total Products: {{total_products}}\n✅ In Stock: {{in_stock}}\n⚠️ Low Stock: {{low_stock}}\n❌ Out of Stock: {{out_of_stock}}\n\n_Generated by EHN One_',
  },
  order_confirmation: {
    name: 'Order Confirmation',
    variables: ['customer_name', 'order_id', 'amount', 'delivery_date'],
    defaultMessage: '✅ *Order Confirmed*\n\nThank you {{customer_name}}!\n\nOrder ID: {{order_id}}\nTotal Amount: ₹{{amount}}\nDelivery Date: {{delivery_date}}\n\nYour invoice is attached.\n\n_EHN One - Thank you for your business!_',
  },
};

export default function Automations() {
  const { can } = useAuth();
  const [automations, setAutomations] = useState(automationsDB);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [editAutomation, setEditAutomation] = useState(null);
  const [viewAutomation, setViewAutomation] = useState(null);
  const [showApiConfigModal, setShowApiConfigModal] = useState(false);
  const [apiConfig, setApiConfig] = useState(whatsappConfig);

  const stats = {
    total: automations.length,
    active: automations.filter(a => a.enabled).length,
    whatsapp: automations.filter(a => a.channel === 'whatsapp').length,
    triggered: automations.reduce((sum, a) => sum + a.triggeredCount, 0),
  };

  const getTypeBadge = (type) => {
    const map = {
      low_stock: { color: 'warning', icon: 'bi-box-seam', label: 'Low Stock' },
      payment_reminder: { color: 'info', icon: 'bi-cash-coin', label: 'Payment' },
      stock_report: { color: 'primary', icon: 'bi-file-earmark-text', label: 'Report' },
      order_confirmation: { color: 'success', icon: 'bi-check-circle', label: 'Order' },
    };
    const t = map[type] || map.low_stock;
    return <span className={`badge-v ${t.color}`}><i className={`bi ${t.icon}`}></i> {t.label}</span>;
  };

  const handleToggle = (id) => {
    const updated = automations.map(a => 
      a.id === id ? { ...a, enabled: !a.enabled } : a
    );
    setAutomations(updated);
    automationsDB = updated;
  };

  const handleDelete = (id) => {
    if (window.confirm('Delete this automation? This action cannot be undone.')) {
      setAutomations(automations.filter(a => a.id !== id));
      automationsDB = automations.filter(a => a.id !== id);
    }
  };

  const handleCreate = (newAuto) => {
    const automation = {
      ...newAuto,
      id: `AUTO-${String(nextAutoNum++).padStart(3, '0')}`,
      triggeredCount: 0,
      lastTriggered: null,
    };
    setAutomations([automation, ...automations]);
    automationsDB = [automation, ...automations];
  };

  const handleUpdate = (updated) => {
    setAutomations(automations.map(a => a.id === updated.id ? updated : a));
    automationsDB = automations.map(a => a.id === updated.id ? updated : a);
  };

  const handleSaveApiConfig = (config) => {
    whatsappConfig = config;
    setApiConfig(config);
  };

  const handleTestMessage = async () => {
    if (!apiConfig.isConfigured) {
      alert('Please configure WhatsApp Business API first');
      return;
    }
    // Simulate API call
    setTimeout(() => {
      alert('✅ Test message sent successfully to ' + automations[0]?.phone);
    }, 1000);
  };

  if (!can('settings.view')) {
    return (
      <div className="empty-state-v" style={{ paddingTop: 80 }}>
        <i className="bi bi-shield-x" style={{ color: 'var(--danger)' }}></i>
        <h5>Access Denied</h5>
        <p>You don't have permission to view automations.</p>
      </div>
    );
  }

  return (
    <div>
      {/* Page Header */}
      <div className="page-header">
        <div className="page-header-top">
          <div>
            <h1 className="page-title">
              <i className="bi bi-lightning-charge me-2" style={{ color: 'var(--primary)' }}></i>
              Automations & Reminders
            </h1>
            <p className="page-subtitle">Setup automated WhatsApp notifications for payments, stock alerts & more</p>
          </div>
          <div className="d-flex gap-2">
            {can('settings.edit') && (
              <>
                <button className="btn-v light" onClick={() => setShowApiConfigModal(true)}>
                  <i className="bi bi-gear"></i>
                  <span>WhatsApp API Config</span>
                </button>
                <button className="btn-v primary" onClick={() => setShowCreateModal(true)}>
                  <i className="bi bi-plus-lg"></i>
                  <span>Create Automation</span>
                </button>
              </>
            )}
          </div>
        </div>
      </div>

      {/* API Status Alert */}
      {!apiConfig.isConfigured && (
        <div className="alert-v warning mb-4">
          <i className="bi bi-exclamation-triangle"></i>
          <div>
            <strong>WhatsApp Business API Not Configured</strong>
            <p style={{ margin: '4px 0 0 0', fontSize: '0.85rem' }}>
              Configure your WhatsApp Business API credentials to start sending automated messages.
            </p>
          </div>
          {can('settings.edit') && (
            <button className="btn-v light" onClick={() => setShowApiConfigModal(true)} style={{ marginLeft: 'auto' }}>
              Configure Now
            </button>
          )}
        </div>
      )}

      {apiConfig.isConfigured && apiConfig.verificationStatus === 'verified' && (
        <div className="alert-v success mb-4">
          <i className="bi bi-check-circle"></i>
          <div>
            <strong>WhatsApp Business API Connected</strong>
            <p style={{ margin: '4px 0 0 0', fontSize: '0.85rem' }}>
              Your WhatsApp Business account is verified and ready to send messages.
            </p>
          </div>
          {can('settings.edit') && (
            <button className="btn-v light" onClick={handleTestMessage} style={{ marginLeft: 'auto' }}>
              <i className="bi bi-send"></i> Test Message
            </button>
          )}
        </div>
      )}

      {/* Stats Cards */}
      <div className="row g-3 mb-4">
        <div className="col-xl-3 col-sm-6">
          <div className="stat-card">
            <div className="stat-card-icon primary">
              <i className="bi bi-lightning-charge"></i>
            </div>
            <div className="stat-card-body">
              <div className="stat-card-label">Total Automations</div>
              <div className="stat-card-value">{stats.total}</div>
            </div>
          </div>
        </div>
        <div className="col-xl-3 col-sm-6">
          <div className="stat-card">
            <div className="stat-card-icon success">
              <i className="bi bi-check-circle"></i>
            </div>
            <div className="stat-card-body">
              <div className="stat-card-label">Active</div>
              <div className="stat-card-value">{stats.active}</div>
            </div>
          </div>
        </div>
        <div className="col-xl-3 col-sm-6">
          <div className="stat-card">
            <div className="stat-card-icon info">
              <i className="bi bi-whatsapp"></i>
            </div>
            <div className="stat-card-body">
              <div className="stat-card-label">WhatsApp Alerts</div>
              <div className="stat-card-value">{stats.whatsapp}</div>
            </div>
          </div>
        </div>
        <div className="col-xl-3 col-sm-6">
          <div className="stat-card">
            <div className="stat-card-icon warning">
              <i className="bi bi-bell"></i>
            </div>
            <div className="stat-card-body">
              <div className="stat-card-label">Total Triggered</div>
              <div className="stat-card-value">{stats.triggered}</div>
            </div>
          </div>
        </div>
      </div>

      {/* Automations List */}
      <div className="row g-3">
        {automations.map((auto) => (
          <div key={auto.id} className="col-lg-6">
            <div className="automation-card">
              <div className="automation-card-header">
                <div className="d-flex align-items-start gap-3">
                  <div className={`automation-icon ${auto.enabled ? 'active' : ''}`}>
                    <i className={`bi ${auto.enabled ? 'bi-lightning-charge-fill' : 'bi-lightning-charge'}`}></i>
                  </div>
                  <div className="flex-grow-1">
                    <div className="d-flex align-items-center gap-2 mb-1">
                      <h6 className="mb-0">{auto.name}</h6>
                      {getTypeBadge(auto.type)}
                    </div>
                    <p className="automation-desc">{auto.description}</p>
                    <div className="automation-meta">
                      <span><i className="bi bi-whatsapp"></i> {auto.phone}</span>
                      <span><i className="bi bi-clock"></i> {auto.frequency}</span>
                      {auto.lastTriggered && (
                        <span><i className="bi bi-bell"></i> {auto.triggeredCount} times</span>
                      )}
                    </div>
                  </div>
                  <div className="form-check form-switch">
                    <input 
                      className="form-check-input" 
                      type="checkbox" 
                      checked={auto.enabled}
                      onChange={() => handleToggle(auto.id)}
                      disabled={!can('settings.edit')}
                    />
                  </div>
                </div>
              </div>
              <div className="automation-card-footer">
                <button className="btn-v-text primary" onClick={() => setViewAutomation(auto)}>
                  <i className="bi bi-eye"></i> View Details
                </button>
                {can('settings.edit') && (
                  <>
                    <button className="btn-v-text primary" onClick={() => setEditAutomation(auto)}>
                      <i className="bi bi-pencil"></i> Edit
                    </button>
                    <button className="btn-v-text danger" onClick={() => handleDelete(auto.id)}>
                      <i className="bi bi-trash"></i> Delete
                    </button>
                  </>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      {automations.length === 0 && (
        <div className="v-card">
          <div className="v-card-body">
            <div className="empty-state-v">
              <i className="bi bi-lightning-charge"></i>
              <h5>No Automations Yet</h5>
              <p>Create your first automation to get started with automated notifications</p>
            </div>
          </div>
        </div>
      )}

      {/* View Modal */}
      {viewAutomation && <ViewAutomationModal automation={viewAutomation} onClose={() => setViewAutomation(null)} />}

      {/* Create/Edit Modal */}
      {showCreateModal && <AutomationFormModal onClose={() => setShowCreateModal(false)} onSave={handleCreate} />}
      {editAutomation && <AutomationFormModal automation={editAutomation} onClose={() => setEditAutomation(null)} onSave={handleUpdate} />}

      {/* WhatsApp API Config Modal */}
      {showApiConfigModal && <WhatsAppApiConfigModal config={apiConfig} onClose={() => setShowApiConfigModal(false)} onSave={handleSaveApiConfig} />}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════
   WHATSAPP API CONFIGURATION MODAL
═══════════════════════════════════════════════════════════ */
function WhatsAppApiConfigModal({ config, onClose, onSave }) {
  const [form, setForm] = useState(config);
  const [testingConnection, setTestingConnection] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  const handleTestConnection = async () => {
    setError('');
    setSuccess('');
    setTestingConnection(true);

    // Simulate API verification
    setTimeout(() => {
      if (form.apiKey && form.phoneNumberId && form.businessAccountId) {
        setSuccess('✅ Connection successful! Your WhatsApp Business API is verified.');
        setForm({ ...form, verificationStatus: 'verified', isConfigured: true });
      } else {
        setError('❌ Connection failed. Please check your credentials.');
        setForm({ ...form, verificationStatus: 'failed' });
      }
      setTestingConnection(false);
    }, 2000);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setError('');

    if (!form.apiKey || !form.phoneNumberId || !form.businessAccountId) {
      setError('Please fill all required fields');
      return;
    }

    onSave(form);
    onClose();
  };

  return (
    <div className="modal-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="modal-box" style={{ maxWidth: 700 }}>
        <div className="modal-box-header">
          <i className="bi bi-whatsapp" style={{ color: '#25D366' }}></i>
          WhatsApp Business API Configuration
          <button className="close-btn" onClick={onClose}>
            <i className="bi bi-x-lg"></i>
          </button>
        </div>
        <form onSubmit={handleSubmit}>
          <div className="modal-box-body">
            {/* Info Card */}
            <div className="v-card mb-3" style={{ background: 'rgba(37, 211, 102, 0.04)', border: '1px solid rgba(37, 211, 102, 0.2)' }}>
              <div className="v-card-body" style={{ padding: '16px' }}>
                <div className="d-flex align-items-start gap-3">
                  <i className="bi bi-info-circle" style={{ fontSize: '1.2rem', color: '#25D366' }}></i>
                  <div style={{ fontSize: '0.85rem', lineHeight: 1.6 }}>
                    <strong>Setup Instructions:</strong>
                    <ol style={{ marginBottom: 0, paddingLeft: '20px', marginTop: '8px' }}>
                      <li>Go to <a href="https://business.facebook.com/wa/manage/home/" target="_blank" rel="noopener noreferrer">Meta Business Suite</a></li>
                      <li>Create or select your WhatsApp Business Account</li>
                      <li>Navigate to API Setup and copy your credentials</li>
                      <li>Paste the credentials below and test the connection</li>
                    </ol>
                  </div>
                </div>
              </div>
            </div>

            {error && (
              <div className="alert-v danger mb-3">
                <i className="bi bi-exclamation-circle"></i> {error}
              </div>
            )}

            {success && (
              <div className="alert-v success mb-3">
                <i className="bi bi-check-circle"></i> {success}
              </div>
            )}

            {/* API Credentials */}
            <div className="form-section-title mb-2">
              <i className="bi bi-key"></i> API Credentials
            </div>
            <div className="row g-3 mb-3">
              <div className="col-12">
                <label className="form-label">
                  WhatsApp Business API Key *
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 400, marginLeft: '8px' }}>
                    (Permanent Access Token)
                  </span>
                </label>
                <input
                  className="form-control"
                  type="password"
                  placeholder="Enter your API access token"
                  value={form.apiKey}
                  onChange={(e) => setForm({ ...form, apiKey: e.target.value })}
                  required
                />
              </div>
              <div className="col-md-6">
                <label className="form-label">Phone Number ID *</label>
                <input
                  className="form-control"
                  placeholder="e.g., 123456789012345"
                  value={form.phoneNumberId}
                  onChange={(e) => setForm({ ...form, phoneNumberId: e.target.value })}
                  required
                />
              </div>
              <div className="col-md-6">
                <label className="form-label">Business Account ID *</label>
                <input
                  className="form-control"
                  placeholder="e.g., 987654321098765"
                  value={form.businessAccountId}
                  onChange={(e) => setForm({ ...form, businessAccountId: e.target.value })}
                  required
                />
              </div>
            </div>

            <div className="form-divider"></div>

            {/* Webhook Configuration */}
            <div className="form-section-title mb-2">
              <i className="bi bi-link-45deg"></i> Webhook Configuration (Optional)
            </div>
            <div className="row g-3 mb-3">
              <div className="col-12">
                <label className="form-label">Webhook URL</label>
                <input
                  className="form-control"
                  placeholder="https://your-domain.com/webhook/whatsapp"
                  value={form.webhookUrl}
                  onChange={(e) => setForm({ ...form, webhookUrl: e.target.value })}
                />
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                  Webhook to receive delivery status and replies
                </div>
              </div>
            </div>

            {/* Connection Status */}
            {form.verificationStatus === 'verified' && (
              <div className="v-card" style={{ background: 'rgba(40, 199, 111, 0.08)', border: '1px solid rgba(40, 199, 111, 0.3)' }}>
                <div className="v-card-body" style={{ padding: '16px' }}>
                  <div className="d-flex align-items-center gap-3">
                    <div style={{ width: 40, height: 40, borderRadius: '50%', background: 'var(--success)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <i className="bi bi-check-lg" style={{ fontSize: '1.2rem', color: 'white' }}></i>
                    </div>
                    <div>
                      <div className="fw-bold" style={{ color: 'var(--success)' }}>Connected & Verified</div>
                      <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                        Your WhatsApp Business API is ready to send messages
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Test Connection Button */}
            <div className="text-center mt-3">
              <button 
                type="button" 
                className="btn-v warning" 
                onClick={handleTestConnection}
                disabled={testingConnection || !form.apiKey || !form.phoneNumberId || !form.businessAccountId}
              >
                {testingConnection ? (
                  <>
                    <span className="spinner-border spinner-border-sm me-2"></span>
                    Testing Connection...
                  </>
                ) : (
                  <>
                    <i className="bi bi-wifi"></i> Test Connection
                  </>
                )}
              </button>
            </div>
          </div>
          <div className="modal-box-footer">
            <button className="btn-v light" type="button" onClick={onClose}>Cancel</button>
            <button 
              className="btn-v primary" 
              type="submit"
              disabled={form.verificationStatus !== 'verified'}
            >
              <i className="bi bi-check-circle"></i> Save Configuration
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════
   VIEW AUTOMATION MODAL
═══════════════════════════════════════════════════════════ */
function ViewAutomationModal({ automation, onClose }) {
  return (
    <div className="modal-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="modal-box" style={{ maxWidth: 600 }}>
        <div className="modal-box-header">
          <i className="bi bi-lightning-charge" style={{ color: 'var(--primary)' }}></i>
          Automation Details
          <button className="close-btn" onClick={onClose}>
            <i className="bi bi-x-lg"></i>
          </button>
        </div>
        <div className="modal-box-body">
          {/* Header */}
          <div className="v-card mb-3" style={{ background: automation.enabled ? 'rgba(115,103,240,0.04)' : 'rgba(75,70,92,0.04)', border: `1px solid ${automation.enabled ? 'rgba(115,103,240,0.2)' : 'var(--border-color)'}` }}>
            <div className="v-card-body" style={{ padding: '20px' }}>
              <div className="d-flex align-items-center gap-3 mb-2">
                <div className={`automation-icon-large ${automation.enabled ? 'active' : ''}`}>
                  <i className="bi bi-lightning-charge-fill"></i>
                </div>
                <div>
                  <h5 className="mb-1">{automation.name}</h5>
                  <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                    {automation.description}
                  </div>
                </div>
              </div>
              <div className="d-flex gap-2">
                <span className={`badge-v ${automation.enabled ? 'success' : 'secondary'}`}>
                  {automation.enabled ? 'Active' : 'Inactive'}
                </span>
                {automation.type === 'low_stock' && <span className="badge-v warning"><i className="bi bi-box-seam"></i> Low Stock</span>}
                {automation.type === 'payment_reminder' && <span className="badge-v info"><i className="bi bi-cash-coin"></i> Payment</span>}
                {automation.type === 'stock_report' && <span className="badge-v primary"><i className="bi bi-file-earmark-text"></i> Report</span>}
                {automation.type === 'order_confirmation' && <span className="badge-v success"><i className="bi bi-check-circle"></i> Order</span>}
              </div>
            </div>
          </div>

          {/* Details */}
          <div className="row g-3 mb-3">
            <div className="col-md-6">
              <label className="form-label">Automation ID</label>
              <div className="info-box">{automation.id}</div>
            </div>
            <div className="col-md-6">
              <label className="form-label">Channel</label>
              <div className="info-box">
                <i className="bi bi-whatsapp" style={{ color: '#25D366', marginRight: '8px' }}></i>
                WhatsApp
              </div>
            </div>
            <div className="col-md-6">
              <label className="form-label">Phone Number</label>
              <div className="info-box">{automation.phone}</div>
            </div>
            <div className="col-md-6">
              <label className="form-label">Frequency</label>
              <div className="info-box text-capitalize">{automation.frequency}</div>
            </div>
            {automation.threshold && (
              <div className="col-md-6">
                <label className="form-label">Stock Threshold</label>
                <div className="info-box">{automation.threshold} units</div>
              </div>
            )}
            {automation.daysBeforeDue && (
              <div className="col-md-6">
                <label className="form-label">Days Before Due</label>
                <div className="info-box">{automation.daysBeforeDue} days</div>
              </div>
            )}
            {automation.time && (
              <div className="col-md-6">
                <label className="form-label">Scheduled Time</label>
                <div className="info-box">{automation.time}</div>
              </div>
            )}
            <div className="col-md-6">
              <label className="form-label">Total Triggered</label>
              <div className="info-box">{automation.triggeredCount} times</div>
            </div>
            {automation.lastTriggered && (
              <div className="col-md-6">
                <label className="form-label">Last Triggered</label>
                <div className="info-box">
                  {new Date(automation.lastTriggered).toLocaleString('en-IN', { 
                    day: 'numeric', month: 'short', year: 'numeric', 
                    hour: '2-digit', minute: '2-digit' 
                  })}
                </div>
              </div>
            )}
          </div>
        </div>
        <div className="modal-box-footer">
          <button className="btn-v light" onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════
   AUTOMATION FORM MODAL (Create/Edit)
═══════════════════════════════════════════════════════════ */
function AutomationFormModal({ automation, onClose, onSave }) {
  const [form, setForm] = useState(automation || {
    type: 'low_stock',
    name: '',
    description: '',
    enabled: true,
    channel: 'whatsapp',
    phone: '',
    frequency: 'immediate',
    threshold: 10,
    daysBeforeDue: 3,
    time: '09:00',
    categories: ['all'],
    includeInvoice: false,
    messageTemplate: 'low_stock_alert',
    customMessage: messageTemplates.low_stock_alert.defaultMessage,
  });
  const [error, setError] = useState('');
  const [showPreview, setShowPreview] = useState(false);
  const [activeTab, setActiveTab] = useState('settings'); // settings, message

  const types = [
    { value: 'low_stock', label: 'Low Stock Alert', icon: 'bi-box-seam', desc: 'Get notified when stock goes below threshold' },
    { value: 'payment_reminder', label: 'Payment Reminder', icon: 'bi-cash-coin', desc: 'Remind customers about pending payments' },
    { value: 'stock_report', label: 'Stock Report', icon: 'bi-file-earmark-text', desc: 'Daily/Weekly inventory summary' },
    { value: 'order_confirmation', label: 'Order Confirmation', icon: 'bi-check-circle', desc: 'Send order confirmation to customers' },
  ];

  const handleTypeChange = (type) => {
    const typeConfig = types.find(t => t.value === type);
    const template = messageTemplates[`${type.replace('_', '_')}`] || messageTemplates.low_stock_alert;
    setForm({
      ...form,
      type,
      name: typeConfig.label,
      description: typeConfig.desc,
      messageTemplate: type,
      customMessage: template.defaultMessage,
    });
  };

  const handleResetMessage = () => {
    const template = messageTemplates[form.type] || messageTemplates.low_stock_alert;
    setForm({ ...form, customMessage: template.defaultMessage });
  };

  const getPreviewMessage = () => {
    let preview = form.customMessage;
    const template = messageTemplates[form.type];
    if (template) {
      template.variables.forEach(variable => {
        const sampleData = {
          product_name: 'Samsung Galaxy S23',
          current_stock: '5',
          threshold: '10',
          customer_name: 'Rajesh Kumar',
          amount: '45,500',
          invoice_number: 'INV-2024-001',
          due_date: '25 Jun 2024',
          date: new Date().toLocaleDateString('en-IN'),
          total_products: '150',
          in_stock: '120',
          low_stock: '20',
          out_of_stock: '10',
          order_id: 'ORD-2024-089',
          delivery_date: '20 Jun 2024',
        };
        preview = preview.replace(new RegExp(`{{${variable}}}`, 'g'), sampleData[variable] || `{{${variable}}}`);
      });
    }
    return preview;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setError('');

    if (!form.name || !form.phone) {
      setError('Please fill all required fields');
      return;
    }

    if (!/^\+?[1-9]\d{1,14}$/.test(form.phone.replace(/[\s-]/g, ''))) {
      setError('Please enter a valid phone number with country code (e.g., +91 98765 43210)');
      return;
    }

    if (!form.customMessage.trim()) {
      setError('Message template cannot be empty');
      return;
    }

    onSave(form);
    onClose();
  };

  return (
    <div className="modal-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="modal-box" style={{ maxWidth: 900 }}>
        <div className="modal-box-header">
          <i className="bi bi-lightning-charge" style={{ color: 'var(--primary)' }}></i>
          {automation ? 'Edit Automation' : 'Create New Automation'}
          <button className="close-btn" onClick={onClose}>
            <i className="bi bi-x-lg"></i>
          </button>
        </div>
        <form onSubmit={handleSubmit}>
          <div className="modal-box-body">
            {error && (
              <div className="alert-v danger mb-3">
                <i className="bi bi-exclamation-circle"></i> {error}
              </div>
            )}

            {/* Tabs */}
            <div className="tabs-v mb-3">
              <button
                type="button"
                className={`tab-v${activeTab === 'settings' ? ' active' : ''}`}
                onClick={() => setActiveTab('settings')}
              >
                <i className="bi bi-sliders"></i> Settings
              </button>
              <button
                type="button"
                className={`tab-v${activeTab === 'message' ? ' active' : ''}`}
                onClick={() => setActiveTab('message')}
              >
                <i className="bi bi-chat-text"></i> Message Template
              </button>
            </div>

            {/* Settings Tab */}
            {activeTab === 'settings' && (
              <>
                {/* Type Selection */}
                <div className="form-section-title mb-2">
                  <i className="bi bi-tag"></i> Automation Type
                </div>
                <div className="automation-type-selector mb-3">
                  {types.map((type) => (
                    <button
                      key={type.value}
                      type="button"
                      className={`automation-type-card${form.type === type.value ? ' selected' : ''}`}
                      onClick={() => handleTypeChange(type.value)}
                    >
                      <i className={`bi ${type.icon}`}></i>
                      <div className="fw-semibold">{type.label}</div>
                      <div className="type-desc">{type.desc}</div>
                    </button>
                  ))}
                </div>

                <div className="form-divider"></div>

                {/* Basic Info */}
                <div className="form-section-title mb-2">
                  <i className="bi bi-info-circle"></i> Basic Information
                </div>
                <div className="row g-3 mb-3">
                  <div className="col-12">
                    <label className="form-label">Automation Name *</label>
                    <input
                      className="form-control"
                      value={form.name}
                      onChange={(e) => setForm({ ...form, name: e.target.value })}
                      required
                    />
                  </div>
                  <div className="col-12">
                    <label className="form-label">Description</label>
                    <textarea
                      className="form-control"
                      rows="2"
                      value={form.description}
                      onChange={(e) => setForm({ ...form, description: e.target.value })}
                    ></textarea>
                  </div>
                </div>

                <div className="form-divider"></div>

                {/* WhatsApp Settings */}
                <div className="form-section-title mb-2">
                  <i className="bi bi-whatsapp"></i> WhatsApp Settings
                </div>
                <div className="row g-3 mb-3">
                  <div className="col-md-6">
                    <label className="form-label">Phone Number *</label>
                    <input
                      className="form-control"
                      placeholder="+91 98765 43210"
                      value={form.phone}
                      onChange={(e) => setForm({ ...form, phone: e.target.value })}
                      required
                    />
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                      Include country code (e.g., +91)
                    </div>
                  </div>
                  <div className="col-md-6">
                    <label className="form-label">Frequency</label>
                    <select 
                      className="form-select" 
                      value={form.frequency}
                      onChange={(e) => setForm({ ...form, frequency: e.target.value })}
                    >
                      <option value="immediate">Immediate</option>
                      <option value="daily">Daily</option>
                      <option value="weekly">Weekly</option>
                      <option value="monthly">Monthly</option>
                    </select>
                  </div>
                </div>

                <div className="form-divider"></div>

                {/* Type-specific Settings */}
                <div className="form-section-title mb-2">
                  <i className="bi bi-sliders"></i> Automation Settings
                </div>
                <div className="row g-3">
                  {form.type === 'low_stock' && (
                    <div className="col-md-6">
                      <label className="form-label">Stock Threshold</label>
                      <input
                        className="form-control"
                        type="number"
                        min="1"
                        value={form.threshold}
                        onChange={(e) => setForm({ ...form, threshold: parseInt(e.target.value) || 10 })}
                      />
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                        Alert when stock falls below this number
                      </div>
                    </div>
                  )}

                  {form.type === 'payment_reminder' && (
                    <div className="col-md-6">
                      <label className="form-label">Days Before Due</label>
                      <input
                        className="form-control"
                        type="number"
                        min="1"
                        max="30"
                        value={form.daysBeforeDue}
                        onChange={(e) => setForm({ ...form, daysBeforeDue: parseInt(e.target.value) || 3 })}
                      />
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                        Send reminder X days before due date
                      </div>
                    </div>
                  )}

                  {form.type === 'stock_report' && form.frequency !== 'immediate' && (
                    <div className="col-md-6">
                      <label className="form-label">Report Time</label>
                      <input
                        className="form-control"
                        type="time"
                        value={form.time}
                        onChange={(e) => setForm({ ...form, time: e.target.value })}
                      />
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                        Time to send daily/weekly reports
                      </div>
                    </div>
                  )}

                  {form.type === 'order_confirmation' && (
                    <div className="col-12">
                      <div className="form-check">
                        <input
                          className="form-check-input"
                          type="checkbox"
                          id="includeInvoice"
                          checked={form.includeInvoice}
                          onChange={(e) => setForm({ ...form, includeInvoice: e.target.checked })}
                        />
                        <label className="form-check-label" htmlFor="includeInvoice">
                          Include invoice PDF with confirmation message
                        </label>
                      </div>
                    </div>
                  )}

                  <div className="col-12">
                    <div className="form-check form-switch">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        id="enabledSwitch"
                        checked={form.enabled}
                        onChange={(e) => setForm({ ...form, enabled: e.target.checked })}
                      />
                      <label className="form-check-label" htmlFor="enabledSwitch">
                        Enable this automation immediately
                      </label>
                    </div>
                  </div>
                </div>
              </>
            )}

            {/* Message Template Tab */}
            {activeTab === 'message' && (
              <>
                <div className="form-section-title mb-2">
                  <i className="bi bi-chat-left-text"></i> Customize Message Template
                  <button type="button" className="btn-v-text primary ms-auto" onClick={handleResetMessage}>
                    <i className="bi bi-arrow-clockwise"></i> Reset to Default
                  </button>
                </div>

                {/* Available Variables */}
                <div className="v-card mb-3" style={{ background: 'rgba(115,103,240,0.04)', border: '1px solid rgba(115,103,240,0.2)' }}>
                  <div className="v-card-body" style={{ padding: '12px 16px' }}>
                    <div className="fw-semibold mb-2" style={{ fontSize: '0.85rem', color: 'var(--primary)' }}>
                      <i className="bi bi-code-slash"></i> Available Variables:
                    </div>
                    <div className="d-flex flex-wrap gap-2">
                      {messageTemplates[form.type]?.variables.map(variable => (
                        <span 
                          key={variable} 
                          className="badge-v light" 
                          style={{ fontSize: '0.8rem', cursor: 'pointer' }}
                          onClick={() => {
                            const textarea = document.getElementById('messageTextarea');
                            const cursorPos = textarea.selectionStart;
                            const textBefore = form.customMessage.substring(0, cursorPos);
                            const textAfter = form.customMessage.substring(cursorPos);
                            setForm({ ...form, customMessage: textBefore + `{{${variable}}}` + textAfter });
                          }}
                          title="Click to insert"
                        >
                          {`{{${variable}}}`}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Message Editor */}
                <div className="row g-3">
                  <div className="col-lg-6">
                    <label className="form-label">Message Template *</label>
                    <textarea
                      id="messageTextarea"
                      className="form-control"
                      rows="12"
                      value={form.customMessage}
                      onChange={(e) => setForm({ ...form, customMessage: e.target.value })}
                      placeholder="Enter your message template with variables..."
                      style={{ fontFamily: 'monospace', fontSize: '0.85rem' }}
                      required
                    ></textarea>
                    <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                      Use markdown: *bold*, _italic_, ~strikethrough~
                    </div>
                  </div>

                  {/* Live Preview */}
                  <div className="col-lg-6">
                    <label className="form-label">
                      Live Preview
                      <button 
                        type="button" 
                        className="btn-v-text info ms-2" 
                        onClick={() => setShowPreview(!showPreview)}
                      >
                        <i className={`bi bi-eye${showPreview ? '-slash' : ''}`}></i>
                      </button>
                    </label>
                    {showPreview && (
                      <div className="whatsapp-preview">
                        <div className="whatsapp-preview-header">
                          <i className="bi bi-whatsapp"></i> WhatsApp Preview
                        </div>
                        <div className="whatsapp-preview-body">
                          <div className="whatsapp-message">
                            {getPreviewMessage().split('\n').map((line, idx) => (
                              <div key={idx}>{line || ' '}</div>
                            ))}
                          </div>
                          <div className="whatsapp-meta">
                            {new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
                            <i className="bi bi-check-all"></i>
                          </div>
                        </div>
                      </div>
                    )}
                    {!showPreview && (
                      <div style={{ 
                        height: '300px', 
                        border: '1px solid var(--border-color)', 
                        borderRadius: '8px', 
                        display: 'flex', 
                        alignItems: 'center', 
                        justifyContent: 'center',
                        color: 'var(--text-muted)',
                        fontSize: '0.9rem'
                      }}>
                        <div className="text-center">
                          <i className="bi bi-eye" style={{ fontSize: '2rem', marginBottom: '8px', display: 'block' }}></i>
                          Click "Live Preview" to see your message
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </>
            )}
          </div>
          <div className="modal-box-footer">
            <button className="btn-v light" type="button" onClick={onClose}>Cancel</button>
            <button className="btn-v primary" type="submit">
              <i className="bi bi-check-circle"></i> {automation ? 'Update' : 'Create'} Automation
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
