import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';

/* Mock Automations Database */
let automationsDB = [
  {
    id: 'AUTO-001',
    type: 'low_stock',
    name: 'Low Stock Alert Notification',
    description: 'Get notified when product stock goes below threshold',
    enabled: true,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'immediate',
    threshold: 10,
    categories: ['all'],
    messageTemplate: 'low_stock_alert',
    customMessage: '🚨 *Low Stock Alert*\n\nProduct: {{product_name}}\nCurrent Stock: {{current_stock}} units\nThreshold: {{threshold}} units\n\nAction Required: Restock immediately.\n\n_EHN One - Inventory System_',
    lastTriggered: new Date('2026-08-10T09:30:00'),
    triggeredCount: 12,
  },
  {
    id: 'AUTO-002',
    type: 'payment_reminder',
    name: 'Customer Payment Due Reminder',
    description: 'Remind customers about pending payments',
    enabled: true,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'daily',
    daysBeforeDue: 3,
    messageTemplate: 'payment_reminder',
    customMessage: '💰 *Payment Reminder*\n\nHello {{customer_name}},\n\nThis is a friendly reminder that payment of *₹{{amount}}* for Invoice #{{invoice_number}} is due on {{due_date}}.\n\nPlease make the payment at your earliest convenience.\n\nThank you!\n_EHN One Team_',
    lastTriggered: new Date('2026-08-14T10:00:00'),
    triggeredCount: 45,
  },
  {
    id: 'AUTO-003',
    type: 'stock_report',
    name: 'Daily Stock Summary Report',
    description: 'Daily summary of inventory status sent to warehouse admin',
    enabled: false,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'daily',
    time: '09:00',
    messageTemplate: 'stock_report',
    customMessage: '📊 *Daily Stock Report*\n\nDate: {{date}}\n\n📦 Total Products: {{total_products}}\n✅ In Stock: {{in_stock}}\n⚠️ Low Stock: {{low_stock}}\n❌ Out of Stock: {{out_of_stock}}\n\n_Generated by EHN One_',
    lastTriggered: new Date('2026-08-13T09:00:00'),
    triggeredCount: 28,
  },
  {
    id: 'AUTO-004',
    type: 'order_confirmation',
    name: 'Sales Invoice Order Confirmation',
    description: 'Send order confirmation and PDF invoice link to customers',
    enabled: true,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'immediate',
    includeInvoice: true,
    messageTemplate: 'order_confirmation',
    customMessage: '✅ *Order Confirmed*\n\nThank you {{customer_name}}!\n\nOrder ID: {{order_id}}\nTotal Amount: ₹{{amount}}\nDelivery Date: {{delivery_date}}\n\nYour invoice is attached.\n\n_EHN One - Thank you for your business!_',
    lastTriggered: new Date('2026-08-13T14:20:00'),
    triggeredCount: 89,
  },
  {
    id: 'AUTO-005',
    type: 'today_summary',
    name: 'Daily Executive Business Summary',
    description: 'Automated daily report of total sales, cash collection, and pending dues sent at day end',
    enabled: true,
    channel: 'whatsapp',
    phone: '+91 98765 43210',
    frequency: 'daily',
    time: '20:00',
    messageTemplate: 'today_summary',
    customMessage: '📊 *DAILY BUSINESS SUMMARY REPORT - EHN One*\n\n📅 Date: {{date}}\n\n🧾 Today\'s Invoices Created: {{invoices_count}}\n💰 Total Sales Revenue: ₹{{total_revenue}}\n✅ Cash / Payment Collected: ₹{{paid_amount}}\n⏳ Pending / Credit Amount: ₹{{pending_amount}}\n\n_Automated Daily Summary Report_',
    lastTriggered: new Date('2026-08-13T20:00:00'),
    triggeredCount: 64,
  },
];

let nextAutoNum = 6;

/* WhatsApp Business API Configuration */
let whatsappConfig = {
  apiKey: '',
  phoneNumberId: '',
  businessAccountId: '',
  webhookUrl: '',
  isConfigured: true,
  verificationStatus: 'verified',
};

export const getWhatsAppConfig = () => whatsappConfig;
export const setWhatsAppConfig = (config) => { whatsappConfig = config; };

/* Message Template Library */
const messageTemplates = {
  low_stock_alert: {
    name: 'Low Stock Alert',
    variables: ['product_name', 'current_stock', 'threshold'],
    defaultMessage: '🚨 *Low Stock Alert*\n\nProduct: {{product_name}}\nCurrent Stock: {{current_stock}} units\nThreshold: {{threshold}} units\n\nAction Required: Restock immediately.\n\n_EHN One - Inventory System_',
  },
  payment_reminder: {
    name: 'Payment Reminder',
    variables: ['customer_name', 'amount', 'invoice_number', 'due_date'],
    defaultMessage: '💰 *Payment Reminder*\n\nHello {{customer_name}},\n\nThis is a friendly reminder that payment of *₹{{amount}}* for Invoice #{{invoice_number}} is due on {{due_date}}.\n\nPlease make the payment at your earliest convenience.\n\nThank you!\n_EHN One Team_',
  },
  stock_report: {
    name: 'Stock Report',
    variables: ['date', 'total_products', 'in_stock', 'low_stock', 'out_of_stock'],
    defaultMessage: '📊 *Daily Stock Report*\n\nDate: {{date}}\n\n📦 Total Products: {{total_products}}\n✅ In Stock: {{in_stock}}\n⚠️ Low Stock: {{low_stock}}\n❌ Out of Stock: {{out_of_stock}}\n\n_Generated by EHN One_',
  },
  order_confirmation: {
    name: 'Order Confirmation',
    variables: ['customer_name', 'order_id', 'amount', 'delivery_date'],
    defaultMessage: '✅ *Order Confirmed*\n\nThank you {{customer_name}}!\n\nOrder ID: {{order_id}}\nTotal Amount: ₹{{amount}}\nDelivery Date: {{delivery_date}}\n\nYour invoice is attached.\n\n_EHN One - Thank you for your business!_',
  },
};

export default function Automations() {
  const { can } = useAuth();
  const [automations, setAutomations] = useState(automationsDB);
  const [search, setSearch] = useState('');
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [editAutomation, setEditAutomation] = useState(null);
  const [viewAutomation, setViewAutomation] = useState(null);
  const [showApiConfigModal, setShowApiConfigModal] = useState(false);
  const [apiConfig, setApiConfig] = useState(whatsappConfig);

  // Keyboard Shortcuts Handler
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (['INPUT', 'TEXTAREA', 'SELECT'].includes(e.target.tagName) && e.key !== 'F2' && !(e.altKey && (e.key === 'w' || e.key === 'W' || e.key === 't' || e.key === 'T' || e.key === 'c' || e.key === 'C'))) return;

      if (e.key === 'F2') {
        e.preventDefault();
        document.getElementById('automation-search-input')?.focus();
      } else if (e.key === 'F4') {
        if (can('settings.edit')) {
          e.preventDefault();
          setShowCreateModal(true);
        }
      } else if (e.key === 'F5') {
        e.preventDefault();
        setAutomations([...automationsDB]);
      } else if (e.altKey && (e.key === 'w' || e.key === 'W')) {
        e.preventDefault();
        setShowApiConfigModal(true);
      } else if (e.altKey && (e.key === 't' || e.key === 'T')) {
        e.preventDefault();
        handleTestMessage();
      } else if (e.altKey && (e.key === 'c' || e.key === 'C')) {
        e.preventDefault();
        exportCSV();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [can]);

  const filteredAutomations = automations.filter((a) => {
    const q = search.toLowerCase();
    return !q || a.name.toLowerCase().includes(q) || a.type.toLowerCase().includes(q) || a.description.toLowerCase().includes(q);
  });

  const stats = {
    total: automations.length,
    active: automations.filter(a => a.enabled).length,
    whatsapp: automations.filter(a => a.channel === 'whatsapp').length,
    triggered: automations.reduce((sum, a) => sum + a.triggeredCount, 0),
  };

  const getTypeBadge = (type) => {
    const map = {
      low_stock: { color: 'warning', icon: 'bi-box-seam', label: 'Low Stock Alert' },
      payment_reminder: { color: 'info', icon: 'bi-cash-coin', label: 'Payment Due Reminder' },
      stock_report: { color: 'primary', icon: 'bi-file-earmark-text', label: 'Stock Report' },
      order_confirmation: { color: 'success', icon: 'bi-check-circle', label: 'Order Confirmation' },
      today_summary: { color: 'primary', icon: 'bi-graph-up', label: 'Executive Summary' },
    };
    const t = map[type] || map.low_stock;
    return <span className={`badge-v ${t.color}`} style={{ fontSize: '0.7rem' }}><i className={`bi ${t.icon} me-1`}></i> {t.label}</span>;
  };

  const handleToggle = (id) => {
    const updated = automations.map(a => 
      a.id === id ? { ...a, enabled: !a.enabled } : a
    );
    setAutomations(updated);
    automationsDB = updated;
  };

  const handleDelete = (id) => {
    if (window.confirm('Delete this automation rule? This cannot be undone.')) {
      setAutomations(automations.filter(a => a.id !== id));
      automationsDB = automations.filter(a => a.id !== id);
    }
  };

  const exportCSV = () => {
    const headers = ['ID', 'Name', 'Type', 'Channel', 'Status', 'Frequency', 'Triggered Count', 'Last Triggered'];
    const rows = automations.map(a => [
      `"${a.id}"`,
      `"${a.name || ''}"`,
      `"${a.type || ''}"`,
      `"${a.channel || ''}"`,
      a.enabled ? 'ACTIVE' : 'DISABLED',
      `"${a.frequency || ''}"`,
      a.triggeredCount || 0,
      `"${a.lastTriggered ? new Date(a.lastTriggered).toLocaleString('en-IN') : 'Never'}"`
    ]);
    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `Automation_Rules_Register_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleTestMessage = async () => {
    alert('✅ Test WhatsApp alert message sent successfully!');
  };

  if (!can('settings.view')) {
    return (
      <div className="empty-state-v" style={{ paddingTop: 80 }}>
        <i className="bi bi-shield-x" style={{ color: 'var(--danger)' }}></i>
        <h5>Access Denied</h5>
        <p>You don't have permission to access automations register.</p>
      </div>
    );
  }

  return (
    <div>
      {/* Gateway of Tally Software Module Header Bar */}
      <div className="tally-header-bar mb-3 shadow-sm">
        <div className="d-flex flex-wrap align-items-center justify-content-between gap-2">
          <div className="d-flex align-items-center gap-2">
            <span className="tally-header-badge" style={{ background: 'var(--primary)', color: '#fff' }}>AUTOMATION</span>
            <div>
              <h5 className="mb-0 fw-bold text-uppercase" style={{ fontSize: '0.95rem', letterSpacing: '0.5px' }}>
                BOT AUTOMATION & REMINDERS REGISTER &mdash; WHATSAPP & SYSTEM ALERTS
              </h5>
              <div className="text-muted small" style={{ fontSize: '0.72rem' }}>
                F.Y. 2026-2027 | Automated Workflow Engine | EHN One ERP
              </div>
            </div>
          </div>
          <div className="d-flex align-items-center gap-2">
            <button className="btn-v outline-secondary btn-sm" onClick={handleTestMessage}>
              <i className="bi bi-send me-1"></i> [Alt+T] Test Message
            </button>
            <button className="btn-v outline-primary btn-sm" onClick={exportCSV}>
              <i className="bi bi-download me-1"></i> [Alt+C] Export CSV
            </button>
            {can('settings.edit') && (
              <button className="btn-v primary btn-sm" onClick={() => setShowCreateModal(true)}>
                <i className="bi bi-plus-lg me-1"></i> [F4] Add Automation Rule
              </button>
            )}
          </div>
        </div>

        {/* F1-F8 Action Toolbar */}
        <div className="tally-toolbar mt-2 pt-2 border-top d-flex gap-2 flex-wrap">
          <button className="tally-shortcut-btn" onClick={() => document.getElementById('automation-search-input')?.focus()}>
            <span className="key">[F2]</span> Search Rule
          </button>
          {can('settings.edit') && (
            <button className="tally-shortcut-btn" onClick={() => setShowCreateModal(true)}>
              <span className="key">[F4]</span> New Rule Master
            </button>
          )}
          <button className="tally-shortcut-btn" onClick={() => setAutomations([...automationsDB])}>
            <span className="key">[F5]</span> Refresh Register
          </button>
          <button className="tally-shortcut-btn" onClick={() => setShowApiConfigModal(true)}>
            <span className="key">[Alt+W]</span> WhatsApp API Config
          </button>
          <button className="tally-shortcut-btn" onClick={handleTestMessage}>
            <span className="key">[Alt+T]</span> Test WhatsApp Alert
          </button>
          <button className="tally-shortcut-btn" onClick={exportCSV}>
            <span className="key">[Alt+C]</span> Export CSV
          </button>
        </div>
      </div>

      {/* Metric Summary Cards */}
      <div className="row g-2 mb-3">
        <div className="col-xl-3 col-sm-6">
          <div className="tally-stat-card">
            <div className="tally-stat-label">TOTAL AUTOMATION RULES</div>
            <div className="tally-stat-value">{stats.total}</div>
            <div className="tally-stat-sub text-muted">Configured Event Triggers</div>
          </div>
        </div>
        <div className="col-xl-3 col-sm-6">
          <div className="tally-stat-card">
            <div className="tally-stat-label">ACTIVE LIVE RULES</div>
            <div className="tally-stat-value text-success">{stats.active}</div>
            <div className="tally-stat-sub text-muted">Enabled Background Triggers</div>
          </div>
        </div>
        <div className="col-xl-3 col-sm-6">
          <div className="tally-stat-card">
            <div className="tally-stat-label">WHATSAPP CHANNELS</div>
            <div className="tally-stat-value text-primary">{stats.whatsapp}</div>
            <div className="tally-stat-sub text-muted">Business API Connected</div>
          </div>
        </div>
        <div className="col-xl-3 col-sm-6">
          <div className="tally-stat-card">
            <div className="tally-stat-label">TRIGGERED MESSAGES</div>
            <div className="tally-stat-value text-info">{stats.triggered}</div>
            <div className="tally-stat-sub text-muted">Total Executed Notifications</div>
          </div>
        </div>
      </div>

      {/* Search & Filter Bar */}
      <div className="v-card mb-3">
        <div className="v-card-body p-2">
          <div className="d-flex align-items-center flex-wrap gap-2">
            <div className="search-box-v flex-grow-1">
              <i className="bi bi-search"></i>
              <input
                id="automation-search-input"
                type="text"
                className="form-control"
                placeholder="Filter automation rules by name, type, description... [Press F2]"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <div className="d-flex align-items-center gap-2">
              <span className="badge-v secondary fw-bold" style={{ fontSize: '0.75rem' }}>
                {filteredAutomations.length} RULES FOUND
              </span>
              <button className="btn-v outline-secondary btn-sm" onClick={() => setAutomations([...automationsDB])}>
                <i className="bi bi-arrow-clockwise me-1"></i> Refresh
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* High-Density Tally Table */}
      <div className="v-card">
        <div className="v-card-header d-flex justify-content-between align-items-center">
          <span><i className="bi bi-lightning-charge me-2" style={{ color: 'var(--primary)' }}></i>AUTOMATION & REMINDER RULES REGISTER</span>
          <span className="text-muted small">HIGH-DENSITY ERP VIEW</span>
        </div>
        <div className="v-card-body p-0" style={{ overflowX: 'auto' }}>
          {filteredAutomations.length === 0 ? (
            <div className="empty-state-v py-4">
              <i className="bi bi-lightning-charge text-muted" style={{ fontSize: '2rem' }}></i>
              <h5 className="fw-bold mt-2 text-uppercase" style={{ fontSize: '0.88rem' }}>No Automation Rules Found</h5>
              <p className="text-muted" style={{ fontSize: '0.8rem' }}>Click "[F4] Add Automation Rule" to configure an event trigger</p>
            </div>
          ) : (
            <table className="v-table">
              <thead>
                <tr>
                  <th style={{ width: 40 }}>#</th>
                  <th>RULE NAME</th>
                  <th>TRIGGER TYPE</th>
                  <th>CHANNEL</th>
                  <th>SCHEDULE / FREQUENCY</th>
                  <th>STATUS</th>
                  <th className="text-end">EXECUTIONS</th>
                  <th className="text-end" style={{ width: 120 }}>ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {filteredAutomations.map((a, i) => (
                  <tr key={a.id}>
                    <td className="text-muted fw-semibold" style={{ fontSize: '0.75rem' }}>{i + 1}</td>
                    <td>
                      <div className="fw-bold text-dark">{a.name}</div>
                      <small className="text-muted d-block" style={{ fontSize: '0.72rem' }}>{a.description}</small>
                    </td>
                    <td>{getTypeBadge(a.type)}</td>
                    <td>
                      <span className="badge-v success" style={{ fontSize: '0.7rem' }}>
                        <i className="bi bi-whatsapp me-1"></i> WhatsApp
                      </span>
                    </td>
                    <td>
                      <span className="badge-v secondary text-uppercase">{a.frequency}</span>
                    </td>
                    <td>
                      <div className="form-check form-switch mb-0">
                        <input
                          className="form-check-input style-cursor"
                          type="checkbox"
                          checked={a.enabled}
                          onChange={() => handleToggle(a.id)}
                          title={a.enabled ? 'Disable Rule' : 'Enable Rule'}
                        />
                        <span className={`badge-v ${a.enabled ? 'success' : 'secondary'} ms-1`} style={{ fontSize: '0.68rem' }}>
                          {a.enabled ? 'ACTIVE' : 'OFF'}
                        </span>
                      </div>
                    </td>
                    <td className="text-end fw-bold text-primary">{a.triggeredCount} msgs</td>
                    <td className="text-end">
                      <div className="d-flex justify-content-end gap-1">
                        <button className="btn-v outline-secondary btn-sm px-2" onClick={() => setViewAutomation(a)} title="View Rule Details">
                          <i className="bi bi-eye"></i>
                        </button>
                        {can('settings.edit') && (
                          <>
                            <button className="btn-v outline-primary btn-sm px-2" onClick={() => setEditAutomation(a)} title="Edit Rule">
                              <i className="bi bi-pencil"></i>
                            </button>
                            <button className="btn-v outline-danger btn-sm px-2" onClick={() => handleDelete(a.id)} title="Delete Rule">
                              <i className="bi bi-trash"></i>
                            </button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>

      {/* View Automation Details Window */}
      {viewAutomation && (
        <div className="modal-overlay" onClick={(e) => { if (e.target === e.currentTarget) setViewAutomation(null); }}>
          <div className="modal-box" style={{ maxWidth: 550 }}>
            <div className="modal-box-header d-flex align-items-center justify-content-between">
              <span>AUTOMATION RULE DETAILS &mdash; {viewAutomation.id}</span>
              <button className="close-btn" onClick={() => setViewAutomation(null)}><i className="bi bi-x-lg"></i></button>
            </div>
            <div className="modal-box-body p-3">
              <div className="mb-3">
                <h6 className="fw-bold mb-1">{viewAutomation.name}</h6>
                <p className="text-muted small mb-2">{viewAutomation.description}</p>
                <div className="d-flex gap-2">{getTypeBadge(viewAutomation.type)}</div>
              </div>
              <div className="p-3 bg-light rounded-2 border mb-3">
                <div className="fw-bold small mb-1 text-muted">WHATSAPP MESSAGE TEMPLATE:</div>
                <pre style={{ whiteSpace: 'pre-wrap', fontSize: '0.78rem', margin: 0, fontFamily: 'inherit' }}>
                  {viewAutomation.customMessage}
                </pre>
              </div>
              <div className="row g-2 small">
                <div className="col-6"><strong>Trigger Channel:</strong> WhatsApp Business API</div>
                <div className="col-6"><strong>Execution Frequency:</strong> {viewAutomation.frequency}</div>
                <div className="col-6"><strong>Total Executions:</strong> {viewAutomation.triggeredCount} messages</div>
                <div className="col-6"><strong>Last Triggered:</strong> {viewAutomation.lastTriggered ? new Date(viewAutomation.lastTriggered).toLocaleString('en-IN') : 'Never'}</div>
              </div>
            </div>
            <div className="modal-box-footer d-flex justify-content-end">
              <button className="btn-v outline-secondary btn-sm" onClick={() => setViewAutomation(null)}>Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
